version: "3.7"

services:

  db:
    # build: ./containers/mariadb/
    image: mariadb:latest
    volumes:
      - data:/var/lib/mysql
    ports:
      - 8081:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  web:
    # build: ./containers/wordpress/
    image: wordpress:php7.3-fpm
    volumes:
      - php:/var/www/html #<container_name>:<mount_point>
    ports:
      - 8080:80
    links:
      - db:data
    environment:
      WORDPRESS_DB_PASSWORD: password

  cli:
    image: wordpress:cli
    volumes:
      - php:/var/www/html #<container_name>:<mount_point>
    links:
      - db:data
    entrypoint: wp  
    command: "--info"

volumes:
    data:
      # driver: local
      # driver_opts:
      #   mountpoint: ./containers/mariadb/data
    php:
