FROM wordpress:php:7.3-fpm

LABEL com.pressingspace.dockerfile.wordpress.version="1.1.0"
LABEL com.pressingspace.dockerfile.wordpress.name="Wordpress Dockerfile"
LABEL com.pressingspace.dockerfile.wordpress.vendor="Pressing Space"
LABEL com.pressingspace.dockerfile.wordpress.maintainer="stu@pressingspace.com"
    
# RUN apt-get -y update \
#     && apt-get install -y --force-yes --no-install-recommends less libxml2-dev

# # Add some standard extensions
# RUN docker-php-ext-install soap
# RUN docker-php-ext-install pdo_mysql

# # Add PHP Intl extension
# RUN apt-get install -y libicu-dev \
#     && docker-php-ext-configure intl \
#     && docker-php-ext-install intl
    
# # Add PHP Zip Archive extension
# RUN apt-get install -y zlib1g-dev \
#     && rm -rf /var/lib/apt/lists/* \
#     && docker-php-ext-install zip

# RUN a2enmod rewrite expires
