FROM mariadb:latest

LABEL com.pressingspace.dockerfile.mariadb.version="1.0.0"
LABEL com.pressingspace.dockerfile.mariadb.name="MariaDb Dockerfile"
LABEL com.pressingspace.dockerfile.mariadb.vendor="Pressing Space"
LABEL com.pressingspace.dockerfile.mariadb.maintainer="stuart.mcalpine@pressingspace.com"
